In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/flo-data/flo_data_20k.csv

In [2]:
df = pd.read_csv("/kaggle/input/flo-data/flo_data_20k.csv")

In [3]:
df.head()

,master_id,order_channel,last_order_channel,first_order_date,last_order_date,last_order_date_online,last_order_date_offline,order_num_total_ever_online,order_num_total_ever_offline,customer_value_total_ever_offline,customer_value_total_ever_online,interested_in_categories_12
0,cc294636-19f0-11eb-8d74-000d3a38a36f,Android App,Offline,2020-10-30,2021-02-26,2021-02-21,2021-02-26,4.0,1.0,139.99,799.38,[KADIN]
1,f431bd5a-ab7b-11e9-a2fc-000d3a38a36f,Android App,Mobile,2017-02-08,2021-02-16,2021-02-16,2020-01-10,19.0,2.0,159.97,1853.58,"[ERKEK, COCUK, KADIN, AKTIFSPOR]"
2,69b69676-1a40-11ea-941b-000d3a38a36f,Android App,Android App,2019-11-27,2020-11-27,2020-11-27,2019-12-01,3.0,2.0,189.97,395.35,"[ERKEK, KADIN]"
3,1854e56c-491f-11eb-806e-000d3a38a36f,Android App,Android App,2021-01-06,2021-01-17,2021-01-17,2021-01-06,1.0,1.0,39.99,81.98,"[AKTIFCOCUK, COCUK]"
4,d6ea1074-f1f5-11e9-9346-000d3a38a36f,Desktop,Desktop,2019-08-03,2021-03-07,2021-03-07,2019-08-03,1.0,1.0,49.99,159.99,[AKTIFSPOR]

In [4]:
df.describe()

,order_num_total_ever_online,order_num_total_ever_offline,customer_value_total_ever_offline,customer_value_total_ever_online
count,19945.000000,19945.000000,19945.000000,19945.000000
mean,3.110855,1.913913,253.922597,497.321690
std,4.225647,2.062880,301.532853,832.601886
min,1.000000,1.000000,10.000000,12.990000
25%,1.000000,1.000000,99.990000,149.980000
50%,2.000000,1.000000,179.980000,286.460000
75%,4.000000,2.000000,319.970000,578.440000
max,200.000000,109.000000,18119.140000,45220.130000

In [5]:
df.columns

Index(['master_id', 'order_channel', 'last_order_channel', 'first_order_date',
       'last_order_date', 'last_order_date_online', 'last_order_date_offline',
       'order_num_total_ever_online', 'order_num_total_ever_offline',
       'customer_value_total_ever_offline', 'customer_value_total_ever_online',
       'interested_in_categories_12'],
      dtype='object')

In [6]:
df.isnull().sum()

master_id                            0
order_channel                        0
last_order_channel                   0
first_order_date                     0
last_order_date                      0
last_order_date_online               0
last_order_date_offline              0
order_num_total_ever_online          0
order_num_total_ever_offline         0
customer_value_total_ever_offline    0
customer_value_total_ever_online     0
interested_in_categories_12          0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19945 entries, 0 to 19944
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   master_id                          19945 non-null  object
 1   order_channel                      19945 non-null  object
 2   last_order_channel                 19945 non-null  object
 3   first_order_date                   19945 non-null  object
 4   last_order_date                    19945 non-null  object
 5   last_order_date_online             19945 non-null  object
 6   last_order_date_offline            19945 non-null  object
 7   order_num_total_ever_online        19945 non-null  float64
 8   order_num_total_ever_offline       19945 non-null  float64
 9   customer_value_total_ever_offline  19945 non-null  float64
 10  customer_value_total_ever_online   19945 non-null  float64
 11  interested_in_categories_12        19945 non-null  object
dtypes: float64(4), object(8)
memory usage: 1.8+ MB

In [8]:
for i in df.columns:
    if 'date' in str(i):
        df[i] = pd.to_datetime(df[i])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19945 entries, 0 to 19944
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   master_id                          19945 non-null  object
 1   order_channel                      19945 non-null  object
 2   last_order_channel                 19945 non-null  object
 3   first_order_date                   19945 non-null  datetime64[ns]
 4   last_order_date                    19945 non-null  datetime64[ns]
 5   last_order_date_online             19945 non-null  datetime64[ns]
 6   last_order_date_offline            19945 non-null  datetime64[ns]
 7   order_num_total_ever_online        19945 non-null  float64
 8   order_num_total_ever_offline       19945 non-null  float64
 9   customer_value_total_ever_offline  19945 non-null  float64
 10  customer_value_total_ever_online   19945 non-null  float64
 11  interested_in_categories_12        19945 non-null  object
dtypes: datetime64[ns](4), float64(4), object(4)
memory usage: 1.8+ MB

In [10]:
df['order_channel'].value_counts()

order_channel
Android App    9495
Mobile         4882
Ios App        2833
Desktop        2735
Name: count, dtype: int64

In [11]:
df['customer_value_total_ever'] = df['customer_value_total_ever_online'] + df['customer_value_total_ever_offline']
df['order_num_total_ever'] = df['order_num_total_ever_online'] + df['order_num_total_ever_offline']

In [12]:
df.groupby('last_order_channel')[['customer_value_total_ever',
                                'order_num_total_ever']].agg(['sum', 'mean'])

                   customer_value_total_ever             order_num_total_ever  \
                                         sum        mean                  sum
last_order_channel
Android App                       5618108.89  828.263142              37320.0
Desktop                           1475927.65  875.401928               9466.0
Ios App                           1415121.42  834.387630               8595.0
Mobile                            2038731.54  642.727472              14195.0
Offline                           4435677.81  671.258748              30643.0


                        mean
last_order_channel
Android App         5.501990
Desktop             5.614472
Ios App             5.067807
Mobile              4.475095
Offline             4.637258

In [13]:
df.sort_values(by = 'customer_value_total_ever').head(10)

,master_id,order_channel,last_order_channel,first_order_date,last_order_date,last_order_date_online,last_order_date_offline,order_num_total_ever_online,order_num_total_ever_offline,customer_value_total_ever_offline,customer_value_total_ever_online,interested_in_categories_12,customer_value_total_ever,order_num_total_ever
1710,08b95b62-a987-11e9-a2fc-000d3a38a36f,Desktop,Offline,2016-12-17,2021-04-21,2016-12-17,2021-04-21,1.0,1.0,24.99,19.99,[],44.98,2.0
14980,0769f8d0-d627-11e9-93bc-000d3a38a36f,Mobile,Mobile,2019-08-17,2020-10-02,2020-10-02,2019-08-17,1.0,1.0,19.99,24.99,[KADIN],44.98,2.0
7693,1e2dd6cc-0b1e-11eb-8ffc-000d3a38a36f,Mobile,Offline,2020-10-10,2021-03-04,2020-10-10,2021-03-04,1.0,1.0,19.99,29.99,"[COCUK, KADIN]",49.98,2.0
19341,0dd9a790-7d63-11ea-80af-000d3a38a36f,Mobile,Offline,2020-04-13,2020-07-19,2020-04-13,2020-07-19,1.0,1.0,39.47,14.00,"[COCUK, KADIN]",53.47,2.0
12666,1af373d6-acbf-11e9-a2fc-000d3a38a36f,Mobile,Mobile,2019-09-01,2021-02-16,2021-02-16,2019-09-01,1.0,1.0,29.99,25.19,[],55.18,2.0
5137,a5e9ca3e-d632-11e9-93bc-000d3a38a36f,Android App,Android App,2019-08-18,2020-07-06,2020-07-06,2019-08-18,1.0,1.0,19.99,35.99,[KADIN],55.98,2.0
12401,d7c2362e-226b-11ea-8523-000d3a38a36f,Android App,Android App,2019-06-29,2020-12-16,2020-12-16,2019-06-29,1.0,1.0,19.99,37.49,[COCUK],57.48,2.0
11138,882c7a06-b0ac-11e9-9757-000d3a38a36f,Android App,Android App,2019-07-27,2020-07-26,2020-07-26,2019-07-27,1.0,1.0,29.99,29.99,[ERKEK],59.98,2.0
17352,6d4b6c68-af67-11eb-bbf8-000d3a38a36f,Android App,Offline,2021-05-07,2021-05-28,2021-05-07,2021-05-28,1.0,1.0,17.99,47.92,[KADIN],65.91,2.0
19761,77dccc5c-a448-11e9-a2fc-000d3a38a36f,Mobile,Mobile,2019-04-19,2020-12-10,2020-12-10,2019-04-19,1.0,1.0,29.99,35.99,[COCUK],65.98,2.0

In [14]:
df.sort_values(by = 'order_num_total_ever').head(10)

,master_id,order_channel,last_order_channel,first_order_date,last_order_date,last_order_date_online,last_order_date_offline,order_num_total_ever_online,order_num_total_ever_offline,customer_value_total_ever_offline,customer_value_total_ever_online,interested_in_categories_12,customer_value_total_ever,order_num_total_ever
19944,740998d2-b1f7-11e9-89fa-000d3a38a36f,Android App,Android App,2019-09-03,2020-06-06,2020-06-06,2019-09-03,1.0,1.0,39.99,221.98,"[KADIN, AKTIFSPOR]",261.97,2.0
6545,0904db6a-8504-11ea-80af-000d3a38a36f,Android App,Offline,2020-04-22,2021-05-28,2020-04-22,2021-05-28,1.0,1.0,50.87,160.97,"[COCUK, KADIN, AKTIFSPOR]",211.84,2.0
6538,ddbe6e62-a453-11e9-a2fc-000d3a38a36f,Android App,Android App,2019-04-20,2021-05-26,2021-05-26,2019-04-20,1.0,1.0,144.98,116.24,[],261.22,2.0
6531,ad0b4f80-8c40-11ea-8f41-000d3a38a36f,Mobile,Offline,2020-05-02,2021-01-18,2020-05-02,2021-01-18,1.0,1.0,100.88,118.98,[COCUK],219.86,2.0
16554,ec5e0cb2-6099-11eb-9b71-000d3a38a36f,Desktop,Offline,2021-01-27,2021-02-08,2021-01-27,2021-02-08,1.0,1.0,185.87,129.98,[ERKEK],315.85,2.0
16555,ca4329b0-bba2-11ea-995f-000d3a38a36f,Ios App,Ios App,2020-06-28,2020-07-22,2020-07-22,2020-06-28,1.0,1.0,160.73,103.99,"[AKTIFCOCUK, ERKEK]",264.72,2.0
6518,05c918ea-a732-11e9-a2fc-000d3a38a36f,Desktop,Offline,2014-12-07,2020-07-25,2014-12-07,2020-07-25,1.0,1.0,40.49,120.98,[KADIN],161.47,2.0
6512,d324e5b4-ac9e-11e9-a2fc-000d3a38a36f,Desktop,Offline,2018-04-23,2021-05-18,2018-04-23,2021-05-18,1.0,1.0,64.99,94.99,[],159.98,2.0
16560,cb094348-56ad-11ea-b9b9-000d3a38a36f,Mobile,Mobile,2019-12-10,2020-11-17,2020-11-17,2019-12-10,1.0,1.0,309.98,231.65,[],541.63,2.0
6505,1734a0dc-3d63-11ea-9e19-000d3a38a36f,Mobile,Mobile,2019-11-16,2021-05-14,2021-05-14,2019-11-16,1.0,1.0,199.99,257.60,[],457.59,2.0

In [15]:
import datetime as dt
df['Recency'] = dt.datetime(2024, 9, 11) - df['last_order_date']
df['Frequency'] = df['order_num_total_ever']
df['Monetary'] = df['customer_value_total_ever']

In [16]:
rfm = df[['master_id', 'Recency','Frequency','Monetary']]

In [17]:
rfm["recency_score"] = pd.qcut(rfm['Recency'], 5, labels=[5, 4, 3, 2, 1])

# 0-100, 0-20, 20-40, 40-60, 60-80, 80-100

rfm["frequency_score"] = pd.qcut(rfm['Frequency'].rank(method="first"), 5, labels=[5, 4, 3, 2, 1])

rfm["monetary_score"] = pd.qcut(rfm['Monetary'], 5, labels=[1, 2, 3, 4, 5])

/tmp/ipykernel_17/2989191341.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm["recency_score"] = pd.qcut(rfm['Recency'], 5, labels=[5, 4, 3, 2, 1])
/tmp/ipykernel_17/2989191341.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm["frequency_score"] = pd.qcut(rfm['Frequency'].rank(method="first"), 5, labels=[5, 4, 3, 2, 1])
/tmp/ipykernel_17/2989191341.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm["monetary_score"] = pd.qcut(rfm['Monetary'], 5, labels=[1, 2, 3, 4, 5])

In [18]:
rfm['rf_Score'] = rfm["recency_score"].astype(str) + rfm["frequency_score"].astype(str)
rfm['rfm_Score'] = rfm["recency_score"].astype(str) + rfm["frequency_score"].astype(str) + rfm["monetary_score"].astype(str)

/tmp/ipykernel_17/303831360.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm['rf_Score'] = rfm["recency_score"].astype(str) + rfm["frequency_score"].astype(str)
/tmp/ipykernel_17/303831360.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm['rfm_Score'] = rfm["recency_score"].astype(str) + rfm["frequency_score"].astype(str) + rfm["monetary_score"].astype(str)

In [19]:
rfm.head()

,master_id,Recency,Frequency,Monetary,recency_score,frequency_score,monetary_score,rf_Score,rfm_Score
0,cc294636-19f0-11eb-8d74-000d3a38a36f,1293 days,5.0,939.37,3,2,4,32,324
1,f431bd5a-ab7b-11e9-a2fc-000d3a38a36f,1303 days,21.0,2013.55,3,1,5,31,315
2,69b69676-1a40-11ea-941b-000d3a38a36f,1384 days,5.0,585.32,2,2,3,22,223
3,1854e56c-491f-11eb-806e-000d3a38a36f,1333 days,2.0,121.97,3,5,1,35,351
4,d6ea1074-f1f5-11e9-9346-000d3a38a36f,1284 days,2.0,209.98,3,5,1,35,351

In [20]:
seg_map = {
    r'[1-2][1-2]': 'hibernating',
    r'[1-2][3-4]': 'at_Risk',
    r'[1-2]5': 'cant_loose',
    r'3[1-2]': 'about_to_sleep',
    r'33': 'need_attention',
    r'[3-4][4-5]': 'loyal_customers',
    r'41': 'promising',
    r'51': 'new_customers',
    r'[4-5][2-3]': 'potential_loyalists',
    r'5[4-5]': 'champions'
}

In [21]:
rfm['segment'] = rfm['rf_Score'].replace(seg_map, regex=True)

/tmp/ipykernel_17/329518254.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm['segment'] = rfm['rf_Score'].replace(seg_map, regex=True)

In [22]:
rfm[["segment", "Recency", "Frequency", "Monetary"]].groupby("segment").agg(["mean", "count"])

                                         Recency        Frequency        \
                                            mean count       mean count
segment
about_to_sleep      1310 days 11:47:29.903536976  1555   8.239228  1555
at_Risk                1444 days 08:38:10.813032  3407   3.237159  3407
cant_loose          1445 days 23:46:43.038524144  1843   2.000000  1843
champions           1215 days 18:18:07.769784176  1390   2.430935  1390
hibernating         1434 days 22:52:25.474860336  2685   7.729609  2685
loyal_customers     1286 days 15:09:10.134048256  2984   2.416220  2984
need_attention      1311 days 19:53:17.569866336   823   3.727825   823
new_customers       1214 days 21:22:14.831460672  1068  11.813670  1068
potential_loyalists 1234 days 18:44:09.814126400  3228   4.603470  3228
promising           1254 days 18:39:40.041580048   962  11.230769   962

                        Monetary
                            mean count
segment
about_to_sleep       1161.303203  1555
at_Risk               482.117667  3407
cant_loose            308.447965  1843
champions             401.959835  1390
hibernating          1081.147304  2685
loyal_customers       378.493204  2984
need_attention        562.142965   823
new_customers        1863.445272  1068
potential_loyalists   724.078829  3228
promising            1648.168680   962

#### Part A

In [23]:
rfm[((rfm["segment"] == "champions") |
    (rfm["segment"] == "loyal_customers")) &
    (rfm["Monetary"] / rfm["Frequency"] > 250)]

,master_id,Recency,Frequency,Monetary,recency_score,frequency_score,monetary_score,rf_Score,rfm_Score,segment
26,7e7732ae-2d78-11eb-8062-000d3a299ebf,1254 days,2.0,532.31,4,5,3,45,453,loyal_customers
55,59fe5f5c-b1c2-11e9-89fa-000d3a38a36f,1293 days,2.0,689.88,3,5,4,35,354,loyal_customers
57,12f0df54-accc-11e9-a2fc-000d3a38a36f,1239 days,2.0,746.94,4,5,4,45,454,loyal_customers
59,5366d676-5403-11eb-9e65-000d3a38a36f,1206 days,2.0,654.89,5,5,3,55,553,champions
99,9c328802-a6ce-11e9-a2fc-000d3a38a36f,1251 days,3.0,845.77,4,4,4,44,444,loyal_customers
...,...,...,...,...,...,...,...,...,...,...
19663,0bad27e2-51a9-11eb-806e-000d3a38a36f,1288 days,2.0,545.27,3,4,3,34,343,loyal_customers
19727,3c2bf5b0-5bb4-11ea-81c0-000d3a38a36f,1329 days,2.0,534.97,3,4,3,34,343,loyal_customers
19789,c69f66a2-305b-11ea-bb28-000d3a38a36f,1242 days,2.0,1165.78,4,4,5,44,445,loyal_customers
19870,597349e4-aac9-11e9-a2fc-000d3a38a36f,1335 days,2.0,539.82,3,4,3,34,343,loyal_customers
19930,ff3dfd6c-cf3d-11ea-a8f0-000d3a38a36f,1227 days,2.0,506.47,5,4,3,54,543,champions

#### Part B

In [24]:
rfm["segment"].unique()

array(['about_to_sleep', 'hibernating', 'loyal_customers', 'at_Risk',
       'cant_loose', 'new_customers', 'potential_loyalists',
       'need_attention', 'champions', 'promising'], dtype=object)

In [25]:
rfm[((rfm["segment"] == "cant_loose") |
    (rfm["segment"] == "hibernating")|
    (rfm["segment"] == "new_customers")) &
    ((rfm["Recency"] > rfm["Recency"].mean()) &
    (rfm["Frequency"] > rfm["Frequency"].mean()))]

,master_id,Recency,Frequency,Monetary,recency_score,frequency_score,monetary_score,rf_Score,rfm_Score,segment
15,13ed97a4-b167-11e9-89fa-000d3a38a36f,1486 days,8.0,932.36,1,1,4,11,114,hibernating
40,6e47c6c2-4f49-11ea-99ba-000d3a38a36f,1385 days,6.0,1099.89,2,2,5,22,225,hibernating
41,6a46e618-16f8-11ea-b4ec-000d3a38a36f,1520 days,15.0,2930.34,1,1,5,11,115,hibernating
54,e7fa4114-e7cc-11e9-8bb8-000d3a38a36f,1491 days,6.0,404.93,1,2,2,12,122,hibernating
72,6fcc04d0-3050-11ea-bb28-000d3a38a36f,1423 days,6.0,805.40,2,2,4,22,224,hibernating
...,...,...,...,...,...,...,...,...,...,...
19888,36c10134-9ea3-11e9-9897-000d3a38a36f,1535 days,9.0,971.85,1,1,4,11,114,hibernating
19932,13a5e98c-a824-11e9-a2fc-000d3a38a36f,1406 days,9.0,1174.00,2,1,5,21,215,hibernating
19933,6d285c64-5e73-11ea-be5b-000d3a38a36f,1418 days,8.0,1114.80,2,1,5,21,215,hibernating
19936,1982ac0e-9f4c-11e9-9897-000d3a38a36f,1536 days,12.0,1618.22,1,1,5,11,115,hibernating
19937,515ca2d8-afdc-11e9-9757-000d3a38a36f,1476 days,6.0,644.87,1,2,3,12,123,hibernating